@extends('layouts.admin')
@section('title', $product->exists ? 'Edit Product' : ($mode === 'quick' ? 'Quick Add Product' : 'Detailed Product'))
@section('content')
<form class="product-editor" method="post" enctype="multipart/form-data" action="{{ $product->exists ? route('admin.products.update',$product) : route('admin.products.store') }}">@csrf @if($product->exists) @method('PUT') @endif
<div class="editor-main panel"><h2>Product details</h2><div class="form-grid">
<label>Name<input name="name" value="{{ old('name',$product->name) }}" required></label><label>Base price<input name="regular_price" type="number" step="0.01" value="{{ old('regular_price',$product->regular_price) }}" required></label>
<label>Status<select name="status">@foreach(['draft','published','scheduled','archived'] as $s)<option @selected(old('status',$product->status)===$s)>{{ $s }}</option>@endforeach</select></label><label>Primary image<input type="file" name="image" accept="image/*"></label>
<label>Category<select name="category_id"><option value="">Optional</option>@foreach($categories as $c)<option value="{{ $c->id }}" @selected(old('category_id',$product->category_id)==$c->id)>{{ $c->name }}</option>@endforeach</select></label><label>Base stock<input name="stock" type="number" min="0" value="{{ old('stock',$product->stock) }}"><small>Automatically becomes the total variant stock when variants exist.</small></label>
@if($mode !== 'quick' || $product->exists)<label>Slug<input name="slug" value="{{ old('slug',$product->slug) }}"></label><label>SKU<input id="base-sku" name="sku" value="{{ old('sku',$product->sku) }}"></label><label>Barcode<input name="barcode" value="{{ old('barcode',$product->barcode) }}"></label><label>Sale price<input name="sale_price" type="number" step="0.01" value="{{ old('sale_price',$product->sale_price) }}"></label><label>Cost price<input name="cost_price" type="number" step="0.01" value="{{ old('cost_price',$product->cost_price) }}"></label><label class="check-card"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$product->is_featured))><span>Featured product</span></label><label class="wide">Description<textarea name="description">{{ old('description',$product->description) }}</textarea></label><label>Filter tags / fabric<input name="tags_text" value="{{ old('tags_text',collect($product->tags)->join(', ')) }}" placeholder="Winter, Lawn, Luxury"></label>
<label class="wide">Collections<select class="admin-multiselect" name="collection_ids[]" multiple>@foreach($collections as $collection)<option value="{{ $collection->id }}" @selected(in_array($collection->id,old('collection_ids',$product->collections?->pluck('id')->all() ?? [])))>{{ $collection->name }}</option>@endforeach</select><small>Search and select one or more collections.</small></label>@endif
</div></div>
@if($mode !== 'quick' || $product->exists)<aside class="variant-panel panel"><div class="variant-head"><div><h2>Variants</h2><p>Each card is an independently stocked sellable item.</p></div><button class="btn secondary" id="add-variant" type="button"><i data-lucide="plus"></i>Add variant</button></div><div id="variant-list">
@foreach(old('variants',$product->variants->map(function($v){$color=$v->optionValues->firstWhere('option.slug','colour');$size=$v->optionValues->firstWhere('option.slug','size');return ['id'=>$v->id,'color'=>$color?->value,'swatch'=>$color?->swatch ?: '#777777','size'=>$size?->value,'sku'=>$v->sku,'regular_price'=>$v->regular_price,'sale_price'=>$v->sale_price,'stock'=>$v->stock,'enabled'=>$v->is_enabled];})->all()) as $i=>$variant)
<article class="variant-card"><input type="hidden" name="variants[{{ $i }}][id]" value="{{ $variant['id'] ?? '' }}"><header><strong>Variant {{ $i+1 }}</strong><button type="button" class="icon-btn icon-btn--danger remove-variant" title="Remove variant"><i data-lucide="trash-2"></i></button></header><div class="variant-grid"><label>Colour<input name="variants[{{ $i }}][color]" value="{{ $variant['color'] }}" required></label><label>Shade<input type="color" name="variants[{{ $i }}][swatch]" value="{{ $variant['swatch'] }}"></label><label>Size<input name="variants[{{ $i }}][size]" value="{{ $variant['size'] }}" placeholder="S, XL, King"></label><label>SKU<input name="variants[{{ $i }}][sku]" value="{{ $variant['sku'] }}" required></label><label>Price<input type="number" step="0.01" name="variants[{{ $i }}][regular_price]" value="{{ $variant['regular_price'] }}" required></label><label>Sale price<input type="number" step="0.01" name="variants[{{ $i }}][sale_price]" value="{{ $variant['sale_price'] }}"></label><label>Stock<input type="number" min="0" name="variants[{{ $i }}][stock]" value="{{ $variant['stock'] }}" required></label><label>Variant image<input type="file" name="variants[{{ $i }}][image]" accept="image/*"></label><label class="check-card"><input type="checkbox" name="variants[{{ $i }}][enabled]" value="1" @checked($variant['enabled'] ?? true)><span>Enabled</span></label></div></article>
@endforeach
</div><div id="variant-empty" class="empty-inline" @if($product->variants->isNotEmpty() || old('variants')) hidden @endif>No variants yet. The base product remains fully sellable.</div></aside>@endif
<div class="editor-actions"><button class="btn" name="action" value="save"><i data-lucide="save"></i>Save Product</button><button class="btn secondary" name="action" value="another"><i data-lucide="copy-plus"></i>Save and Add Another</button></div></form>
<template id="variant-template"><article class="variant-card"><header><strong>New variant</strong><button type="button" class="icon-btn icon-btn--danger remove-variant" title="Remove variant"><i data-lucide="trash-2"></i></button></header><div class="variant-grid"><label>Colour<input data-name="color" required></label><label>Shade<input type="color" data-name="swatch" value="#777777"></label><label>Size<input data-name="size" placeholder="S, XL, King"></label><label>SKU<input data-name="sku" required></label><label>Price<input type="number" step="0.01" data-name="regular_price" required></label><label>Sale price<input type="number" step="0.01" data-name="sale_price"></label><label>Stock<input type="number" min="0" data-name="stock" value="0" required></label><label>Variant image<input type="file" data-name="image" accept="image/*"></label><label class="check-card"><input type="checkbox" data-name="enabled" value="1" checked><span>Enabled</span></label></div></article></template>
@endsection
@push('scripts')<script>
(()=>{const list=document.querySelector('#variant-list'),add=document.querySelector('#add-variant'),empty=document.querySelector('#variant-empty'),tpl=document.querySelector('#variant-template');if(!list||!add)return;let index=list.children.length;const bind=card=>card.querySelector('.remove-variant').addEventListener('click',()=>{card.remove();empty.hidden=list.children.length>0});list.querySelectorAll('.variant-card').forEach(bind);add.addEventListener('click',()=>{const card=tpl.content.firstElementChild.cloneNode(true);card.querySelectorAll('[data-name]').forEach(input=>{input.name=`variants[${index}][${input.dataset.name}]`});const sku=document.querySelector('#base-sku')?.value||'TB';card.querySelector('[data-name="sku"]').value=`${sku}-V${index+1}`;card.querySelector('[data-name="regular_price"]').value=document.querySelector('[name="regular_price"]').value;bind(card);list.append(card);empty.hidden=true;window.renderAdminIcons?.();index++})})();
</script>@endpush
